prometheus:
  prometheusSpec:
    podMonitorSelector:
      matchLabels:
        team: monitoring
    serviceMonitorSelector:
      matchLabels:
        team: monitoring

# Disable grafana
grafana:
  enabled: false

# Disable node exporter
nodeExporter:
  enabled: false

# Disable alertmanager
alertmanager:
  enabled: false

# Disable Etcd metrics
kubeEtcd:
 enabled: false

# Disable Controller metrics
kubeControllerManager:
 enabled: false

# Disable Scheduler metrics
kubeScheduler:
 enabled: false

# Disable kube state metrics
kubeStateMetrics:
  enabled: false
