---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: traefik
  name: traefik-ingress-controller
  labels:
    app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-ingress-lb
  template:
    metadata:
      labels:
        name: traefik-ingress-lb
        app: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
        - image: traefik:v2.2
          name: traefik-ingress-lb
          imagePullPolicy: Always
          args:
            - --global.checknewversion=false
            - --global.sendanonymoususage=false
            - --log.level=DEBUG
            - --entrypoints.http.address=:80
            - --entrypoints.https.address=:443
            - --entrypoints.https.http.tls
            - --providers.kubernetescrd
            - --api.dashboard
            - --ping
            - --metrics.prometheus
          ports:
            - name: traefik-http
              containerPort: 80
            - name: traefik-api
              containerPort: 8080
            - name: traefik-https
              containerPort: 443
          readinessProbe:
            httpGet:
              path: /ping
              port: traefik-api
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /ping
              port: traefik-api
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
