---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-operator
  name: prometheus-operator
  namespace: monitoring
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    team: monitoring
  name: service-monitor-prometheus-opeator
  namespace: monitoring
spec:
  endpoints:
    - honorLabels: true
      port: http
      path: /metrics
      interval: 15s
  selector:
    matchLabels:
      app: prometheus-operator
