---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    team: monitoring
  name: traefik-pod-monitor
  namespace: traefik
spec:
  namespaceSelector:
    matchNames:
      - traefik
  podMetricsEndpoints:
    - port: traefik
      path: /metrics
      interval: 15s
  selector:
    matchLabels:
      app: traefik
